name: Financials Auto Bulk

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year (e.g. 2024)"
        type: number
        required: true
      months_csv:
        description: "Comma-separated months (e.g. 1,2,3)"
        type: string
        required: true

permissions:
  contents: write

concurrency:
  group: bulk-manual
  cancel-in-progress: false

jobs:
  bulk:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip pandas pyarrow requests beautifulsoup4 lxml ixbrlparse

      - name: Cache CH monthly zips
        uses: actions/cache@v4
        with:
          path: _cache
          key: ${{ format('ch-{0}-{1}', inputs.year, inputs.months_csv) }}

      - name: Run bulk
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p _cache
          python -m scripts.ixbrl_bulk_parse \
            --year ${{ inputs.year }} \
            --months "${{ inputs.months_csv }}" \
            --max-workers 12 \
            --cache-dir _cache
