name: Metadata Bulk

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year (e.g. 2025)"
        required: true
        type: number
      half:
        description: "Half (H1 or H2)"
        required: true
        type: choice
        options: [H1, H2]
      refresh:
        description: "Refetch all (ignore existing metadata asset)"
        required: false
        type: boolean
      limit:
        description: "Optional cap on number of companies (testing)"
        required: false
        type: number

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip pandas pyarrow requests

      - name: Bulk metadata enrich
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.metadata_bulk_enrich \
            --year ${{ inputs.year }} \
            --half ${{ inputs.half }} \
            ${{ inputs.refresh && '--refresh' || '' }} \
            ${{ inputs.limit && format('--limit {0}', inputs.limit) || '' }}
