# .github/workflows/metadata_bulk.yml
name: Metadata API Fill

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year (e.g. 2025)"
        required: true
        type: string
      half:
        description: "Half"
        required: true
        type: choice
        options: [H1, H2]
      max_rpm:
        description: "Max requests per minute (safe 8–15)"
        required: false
        type: string
        default: "10"
      batch_size:
        description: "Checkpoint every N rows"
        required: false
        type: string
        default: "300"
      limit:
        description: "Optional cap for testing"
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: python -m pip install -U pip pandas pyarrow requests

      - name: API fill missing metadata
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
          # if max_rpm is empty, leave it unset — script falls back to 10
          CH_MAX_RPM: ${{ inputs.max_rpm }}
        shell: bash
        run: |
          EXTRA=""
          if [ -n "${{ inputs.limit }}" ]; then
            EXTRA="--limit ${{ inputs.limit }}"
          fi

          python -m scripts.metadata_bulk_api_fill \
            --year "${{ inputs.year }}" \
            --half "${{ inputs.half }}" \
            --batch-size "${{ inputs.batch_size }}" \
            $EXTRA
