name: Metadata Refresh (Snapshot + API)

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:
    inputs:
      year:
        description: "Year (blank = current)"
        required: false
        type: string
        default: ""
      half:
        description: "Half (leave blank to run both)"
        required: false
        type: choice
        options: [H1, H2]
        default: ""
      limit:
        description: "API cap per run (0 = unlimited; use time budget)"
        required: false
        type: string
        default: "0"
      max_rpm:
        description: "Max requests/min (10–15 recommended)"
        required: false
        type: string
        default: "12"
      batch_size:
        description: "Checkpoint size (uploads per run)"
        required: false
        type: string
        default: "600"
      time_budget_mins:
        description: "Stop API fill after N minutes (default 350 ≈ 5h50m)"
        required: false
        type: string
        default: "350"
      no_advanced:
        description: "Skip advanced-search enrichment (faster)"
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  # ---- Scheduled: always run both halves via matrix ----
  scheduled:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        half: [H1, H2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -U pandas pyarrow requests urllib3 certifi
      - name: Snapshot + API refresh (scheduled)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
          CH_MAX_RPM: "12"
          TIME_BUDGET_MINS: "350"
        run: |
          python -m scripts.metadata_snapshot_and_fill \
            --half "${{ matrix.half }}" \
            --limit "0" \
            --batch-size "600" \
            --max-rpm "${CH_MAX_RPM}" \
            --time-budget-mins "${TIME_BUDGET_MINS}" \
            --no-advanced

  # ---- Manual: run exactly one half if user chose one ----
  manual_single:
    if: github.event_name == 'workflow_dispatch' && inputs.half != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -U pandas pyarrow requests urllib3 certifi
      - name: Snapshot + API refresh (manual single)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          YEAR_ARG=""
          if [ -n "${{ inputs.year }}" ]; then
            YEAR_ARG="--year ${{ inputs.year }}"
          fi
          ADV_ARG=""
          if [ "${{ inputs.no_advanced }}" = "true" ]; then
            ADV_ARG="--no-advanced"
          fi
          python -m scripts.metadata_snapshot_and_fill \
            $YEAR_ARG \
            --half "${{ inputs.half }}" \
            --limit "${{ inputs.limit }}" \
            --batch-size "${{ inputs.batch_size }}" \
            --max-rpm "${{ inputs.max_rpm }}" \
            --time-budget-mins "${{ inputs.time_budget_mins }}" \
            $ADV_ARG

  # ---- Manual: if user left half blank, run both halves via matrix ----
  manual_both:
    if: github.event_name == 'workflow_dispatch' && inputs.half == ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        half: [H1, H2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -U pandas pyarrow requests urllib3 certifi
      - name: Snapshot + API refresh (manual both)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          YEAR_ARG=""
          if [ -n "${{ inputs.year }}" ]; then
            YEAR_ARG="--year ${{ inputs.year }}"
          fi
          ADV_ARG=""
          if [ "${{ inputs.no_advanced }}" = "true" ]; then
            ADV_ARG="--no-advanced"
          fi
          python -m scripts.metadata_snapshot_and_fill \
            $YEAR_ARG \
            --half "${{ matrix.half }}" \
            --limit "${{ inputs.limit }}" \
            --batch-size "${{ inputs.batch_size }}" \
            --max-rpm "${{ inputs.max_rpm }}" \
            --time-budget-mins "${{ inputs.time_budget_mins }}" \
            $ADV_ARG
