name: Sample Monthly Concepts

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Monthly archive URL (e.g., https://download.companieshouse.gov.uk/Accounts_Monthly_Data-January2025.zip)"
        required: true
        type: string
      limit:
        description: "Max HTML files to scan"
        required: false
        default: "300"
        type: string
      mincount:
        description: "Only show concepts appearing at least this many times (console)"
        required: false
        default: "5"
        type: string

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install requests pandas beautifulsoup4 lxml

      - name: Run diagnostics
        run: |
          set -e
          python scripts/sample_ixbrl_month.py \
            --url "${{ inputs.url }}" \
            --limit "${{ inputs.limit }}" \
            --mincount "${{ inputs.mincount }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ixbrl-concepts
          path: |
            concept_counts.csv
            concept_samples.txt
          if-no-files-found: warn
